---
title: "Dissertation Analysis Homepage"
author: "Dave Braun"
date: "7/21/2019"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    include:
      in_header: favicon.html
      after_body: footer.html
knit:
  (function(inputFile, encoding) {
      rmarkdown::render(inputFile,
                    encoding = encoding,
                    output_file = 'index.html')})
---

This document is dedicated to organizing all the analyses of my dissertation.   

My aspirations for this document are to make a multi-layered experience, where you can either get the quick highlights of an analysis or dive in for the full thing. For now (7/21), I'm just linking to the full analyses organized by experiment and type of analysis.  

# {.tabset}
## Experiment 1
### Preprocessing  
* [Preprocessing](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/preprocessing/){target=_blank}  
  * The basic subject and RT-based trial trimming that was proposed in the document.  

### Confirmatory Analyses
* [Choice Analyses](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/confirmatory/choice/){target=_blank}  
  * The core 2 (difficulty) X 2 (difference) ANOVA that was proposed in the document.  
* [Performance Analyses](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/confirmatory/performance/){target=_blank}  
  * The 2 (difficulty) X 2 (difference) X 2 (transition) ANOVA (on RTs) that was proposed in the document.  

### Auxiliary Analyses
* [Practice Cued Task Switching Analysis](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/auxiliary/pracCued/){target=_blank}  
  * Testing for the switch cost for both RTs and error rates.
* [Moving Reference Point Analysis](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/auxiliary/movingReference/){target=_blank}  
  * An analysis of whether the reference point might be shifting over time by looking for evidence of order effects in the choice data.  
* [Learning Rate Analysis](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/auxiliary/learning/){target=_blank}  
  * A breakdown of deck selection over trials in a block. Looking for some basic evidence in favor of the idea that people might be faster to learn effort intensities that are harder (rather than easier) than the reference intensity.  

### Exploratory Analyses
Coming soon.

### Demographics Summary
* [Demographics Summary](https://davebraun.org/dissertation/experiments/analysis/exp1/scripts/demo/){target=_blank}  
  * A summary of the basic information collected in the survey at the end of the experiment.

## Experiment 2
### Preprocessing
* [Preprocessing](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/preprocessing/){target=_blank}  
  * The basic subject and RT-based trial trimming that was proposed in the document.  

### Confirmatory  
* [Confirmatory Choice Analyses](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/confirmatory/choice/){target=_blank}  
  * The core 2 (difficulty) X 2 (difference) ANOVA that was proposed in the document.  
  * [Bayesian t-tests](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/confirmatory/bayes/){target=_blank}
    * Using Bayesian t-tests to investigate some of the null choice results.
* [Confirmatory Performance Analyses](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/confirmatory/performance){target=_blank}

### Auxiliary  
* [Practice Cued Task Switching Analysis](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/auxiliary/pracCued/){target=_blank}  
  * Testing for the switch cost for both RTs and error rates.

### Exploratory
* [Exploratory Rapid Fire Choice Analysis](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/exploratory/rapidFire/){target=_blank}  
  * Exploring the choice data from the rapid fire phase, and making subject-wise exclusions based on choice data from both DST and rapid fire.
* [Exploratory Random Effects Analysis](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/exploratory/randomEffects/){target=_blank}
  * Fitting generalized linear mixed models to the choice data in an effort to control for between-subject variance in the predicted effects.  
* [Exploratory Choice Analysis]((https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/exploratory/choice/){target=_blank}  
  * Trying to break down the subject data by trial in the experiment. It seems like selection strategies didn't change much over time.

### Demographics Summary
* [Demographics Summary](https://davebraun.org/dissertation/experiments/analysis/exp2/scripts/demo/){target=_blank}  
  * A summary of the basic information collected in the survey at the end of the experiment.

## Experiment 3

### Pilot
* [Pilot](https://davebraun.org/dissertation/experiments/production/pilots/exp3Pilot/analysis/scripts/demo/){target=_blank}  
  * A 25-participant pilot was conducted to assess the clarity of the instructions and manipulations.

### Preprocessing  
* [Preprocessing](https://davebraun.org/dissertation/experiments/analysis/exp3/scripts/preprocessing/){target=_blank}  
  * The basic subject and RT-based trial trimming that was proposed in the document.  

### Confirmatory
* [Confirmatory Choice Analyses](https://davebraun.org/dissertation/experiments/analysis/exp3/scripts/confirmatory/choice/){target=_blank}  
  * The core 2 (difficulty) X 2 (difference) ANOVA that was proposed in the document.  
* [Confirmatory Performance Analyses](https://davebraun.org/dissertation/experiments/analysis/exp3/scripts/confirmatory/performance){target=_blank}

### Auxiliary  
* [Practice Cued Task Switching Analysis](https://davebraun.org/dissertation/experiments/analysis/exp3/scripts/auxiliary/pracCued/){target=_blank}  
  * Testing for the switch cost for both RTs and error rates.

### Exploratory
* [Exploratory Rapid Fire Choice Analysis](https://davebraun.org/dissertation/experiments/analysis/exp3/scripts/exploratory/rapidFire/){target=_blank}  
  * Exploring the choice data from the rapid fire phase, and making subject-wise exclusions based on choice data from both DST and rapid fire.

### Demographics Summary
* [Demographics Summary](https://davebraun.org/dissertation/experiments/analysis/exp3/scripts/demo/){target=_blank}  
  * A summary of the basic information collected in the survey at the end of the experiment.







