---
title: "Choice Over Time Analyses Exp 3 PyPool"
author: "Dave Braun"
date: "1/5/2022"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    includes:
      after_body: ../../../../footer.html
      in_header: ../../../../favicon.html
knit:
  (function(inputFile, encoding) {
      rmarkdown::render(inputFile,
                    encoding = encoding,
                    output_file = 'index.html')})
---

*This document was last updated at `r Sys.time()`.*

This document is dedicated to looking at the central impact of framing on choice over time in the experiment. An initial look at this has revealed that the central effect looks as though it may be a learned effect.

```{r}
library(tidyverse)

d <- read.csv('../../../data/dstCleanChoice1.csv')

head(d)

N <- length(unique(d$subject))

## what proportion of subjects align with general trend

aligned_subjects <- d %>% 
  group_by(subject, difficulty) %>% 
  summarize(srd = mean(selectedRiskyDeck)) %>% 
  spread(difficulty, srd) %>% 
  filter(`Easier than Reference` > `Harder than Reference`) %>% 
  select(subject)

aligned_subjects <- aligned_subjects$subject

aligned_count <- length(aligned_subjects)

print(paste0(round((aligned_count / N) * 100, 2), '% of subjects are aligned with general trend.'))



```


```{r}

## look at stuff over time ##
whole <- d
d <- d[d$subject %in% aligned_subjects,]

## start with raw data

d$aligned <- ifelse((d$difficulty == 'Easier than Reference' & d$selectedRiskyDeck == 1) | (d$difficulty == 'Harder than Reference' & d$selectedRiskyDeck == 0), 'Aligned', 'Not Aligned')

s <- d[d$subject %in% aligned_subjects[1:5], c('subject', 'difficulty', 'selectedRiskyDeck', 'choiceTrial', 'aligned')]

d %>% 
  
  ggplot(aes(x = choiceTrial, y = aligned)) + 
  #geom_line(aes(group = subject)) + 
  geom_jitter(width = .15, height = .1, alpha = .2) + 
  labs(
    x = 'Trial',
    y = 'Selected Risky Deck'
  ) #+ 
  #facet_grid(rows = vars(subject)) +
  #scale_color_manual(values = c('Aligned' = 'Green', 'Not Aligned' = 'Red'))



  
```


```{r}

## average across subjects

d %>% 
  group_by(difficulty, choiceTrial) %>% 
  summarize(srd = mean(selectedRiskyDeck), se = sd(selectedRiskyDeck) / sqrt(aligned_count)) %>% 
  ggplot(aes(x = choiceTrial, y = srd)) + 
  geom_ribbon(aes(ymin = srd - se, ymax = srd + se, fill = difficulty), alpha = .2) + 
  geom_line(aes(color = difficulty)) + 
  ylim(0, 1) + 
  labs(
     x = 'Trial', 
     y = 'Proportion Selected Risky Deck',
     color = 'Direction',
     fill = 'Direction',
     caption = 'This is only for those subjects who show the overall trend.'
  ) + 
  theme_bw() + 
  theme(legend.position = c(.1,.2))

```



```{r}

whole %>% 
  mutate(ssd = 1 - selectedRiskyDeck) %>% 
  group_by(difficulty, choiceTrial) %>% 
  summarize(ssd_ = mean(ssd), se = sd(ssd) / sqrt(aligned_count)) %>% 
  ggplot(aes(x = choiceTrial, y = ssd_)) + 
  geom_ribbon(aes(ymin = ssd_ - se, ymax = ssd_ + se, group = difficulty), alpha = .2) + 
  geom_line(aes(linetype = difficulty)) + 
  ylim(0, 1) + 
  labs(
    x = 'Trial', 
    y = 'Proportion Selected Safe Deck',
    linetype = 'Direction'
  ) + 
  theme_bw() + 
  theme(legend.position = c(.2,.8),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        text = element_text(size = 16))
  

whole$choiceTrial_c <- whole$choiceTrial - 20
whole$ssd <- 1 - whole$selectedRiskyDeck

ggsave('exp3-pypool_choice_time.pdf', height = 5.5, width = 7.5)
```

```{r}
whole$difficulty_dummy <- ifelse(whole$difficulty == 'Harder than Reference', 1, 0)

m1 <- glm(ssd ~ choiceTrial_c * difficulty_dummy, data = whole, family = binomial(link = 'logit'))
print(summary(m1))
print(exp(m1$coefficients))
print(exp(confint(m1)))

whole$choiceTrial_low <- whole$choiceTrial - 1
whole$choiceTrial_high <- whole$choiceTrial - 40

m_low <- glm(ssd ~ choiceTrial_low * difficulty_dummy, data = whole, family = binomial(link = 'logit'))
print('Centered Low:')
print(summary(m_low))
print(exp(m_low$coefficients))
print(exp(confint(m_low)))

m_high <- glm(ssd ~ choiceTrial_high * difficulty_dummy, data = whole, family = binomial(link = 'logit'))
print('Centered High:')
print(summary(m_high))
print(exp(m_high$coefficients))
print(exp(confint(m_high)))

```







































