---
title: "`r paste('Experiment', ifelse(stringr::str_detect(getwd(), 'exp3'), 3, 2), 'Exploratory Controlling for Error')`"
author: "Dave Braun"
date: "12/07/2022"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    includes:
      after_body: ../../../../footer.html
      in_header: ../../../../favicon.html
knit:
  (function(inputFile, encoding) {
      rmarkdown::render(inputFile,
                    encoding = encoding,
                    output_file = 'index.html')})
---
```{r include = FALSE}
library(tidyverse)
library(ez)
library(car)
```

*This document was last updated at `r Sys.time()`.*

In this document I'm attempting to control for individual differences in error rates in predicting choice using a logistic regression.

```{r}
d <- read.csv('../../../data/dstCleanErrors.csv')
N <- d %>% 
  group_by(subject) %>% 
  summarize(n()) %>% 
  nrow()
head(d)
colnames(d)[colnames(d) %in% c('difference', 'difficulty')]  <- c('magnitude', 'direction')
```

**The sample size is `r N`.**


```{r}
keep <- c('subject', 'choiceTrial', 'cuedTrial', 'cuedRt', 
          'direction', 'magnitude', 'error', 'selectedRiskyDeck')

d <- d[,keep]

d <- d %>% 
  group_by(subject) %>% 
  summarize(error_m = mean(error)) %>% 
  inner_join(d) 

d$error_c <- scale(d$error_m)[,1]
d %>% 
  group_by(subject) %>% 
  summarize(error = mean(error_c)) %>% 
  ggplot(aes(x = error)) +
  geom_histogram(color = 'black', fill = 'steelblue', alpha = .8) + 
  labs(
    x = 'Error',
    y = 'Count'
  ) + 
  theme_bw() 
```


```{r}
## summarize to choice trial
d <- d %>% 
  mutate(ssd = 1 - selectedRiskyDeck) %>% 
  group_by(subject, choiceTrial) %>% 
  summarize(error_c = mean(error_c), direction = unique(direction), magnitude = unique(magnitude),
            ssd = mean(ssd))
```

```{r}
## model

m1 <- glm(ssd ~ direction * magnitude * error_c, data = d, family = binomial(link = 'logit'))
summary(m1)
exp(m1$coefficients)
exp(confint(m1))


## follow ups

## center high
d$error_h <- d$error_c - 1
## center low
d$error_l <- d$error_c + 1

m_l <- glm(ssd ~ direction * magnitude * error_l, data = d, family = binomial(link = 'logit'))
m_h <- glm(ssd ~ direction * magnitude * error_h, data = d, family = binomial(link = 'logit'))




```
Centering high
```{r}
summary(m_h)
exp(m_h$coefficients)
exp(confint(m_h))
```


Centering low
```{r}
summary(m_l)
exp(m_l$coefficients)
exp(confint(m_l))
```





















